services:
- docker
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
- cd ..
- git clone --single-branch --branch master https://github.com/tulibraries/ansible-playbook-solrcloud.git
- mkdir -p ansible-playbook-solrcloud/data/tmp/collections
- cp -r tul_cob-web-solr ansible-playbook-solrcloud/data/tmp/collections/
install:
- cd ansible-playbook-solrcloud
- make build
- bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8090/solr)"
  != "302" ]]; do sleep 5; done'
- make create-local-collections
- make create-aliases
- cd ..
script:
- curl http://localhost:8090/solr/funcake/admin/ping | jq .status
after_success:
- true
before_deploy:
- cd tul_cob-web-solr
deploy:
- provider: script
  script: bash .travis/deploy-stage.sh
  on:
    branch: master
- provider: script
  script: bash .travis/deploy-prod.sh
  on:
    tags: true
    branch:
    - "/^[0-9]$/"
notifications:
  slack:
    rooms:
    - secure: t2abp4n0V4MbZoWj3wnYq5HgB8eednKfGJryJsvYUkhlmXSu6kr+P1RtrAPxUpK1IeH4rjpVLIFfRgEaV9WlMP/8A4Vedc4SgFJTpZ1WjGW0BFk0jndbrHsJ5UogqHnjA1kq7PTg5JRg8K1MZiasNko/MEhGlIUGVp7BN9bNJVj/fP4KiMCF1NM23TB/a5G3eKu9PB2Xaz6nEoucbcwTJU2ns8qi1Ow1IFHqe4832nDnrztogbnH18423v727ce2J2+cuv9Xc+i07CNg8A5W8sWSrAEHytNprciOOvignbHlNMUb9iBZx0TV6Xu6Cy2dbUOpo95ItgTykiXgFDnJWOphQVMPPsrsUxM5eMjbh/da6A34WpStQdiTS0idQjfpOO3vz8vHAyOsIubl/cwvg9qkXgwRqOtU7HXFShqY7FFvPe8NP7ZeHhV2VL8vGpEZ1PzfidiFgux2sVcZPEXEX3L3lDAsCspzNJq8KH/aTshD6le0XloYGyPu2JxUBsr+HauLnI/a1Z2HTHRgK0SF/6NQP+IcIMurMx3RTjbAcpWOLHt4fAAL8XS/8RiwleG55gHNchKhpwb7tzmbHTuwXiDkI18nl1An70vHfUh2duZL+LbVcdHXaAiT+vbYZtLoNOuYaUd0dnl7EjeB4O7LtVDBO1BNrpuu+HsOI4A7NTg=
    - secure: LvfhiKQd8OGrJ6TTIC/Gwkuj90WoZitApB4UPxJZZD7Vz63YhAl7T8gXKcMEymwEAkEO0SWOkghasEh06SJqcdjvnpYVDAEMZPepHqpFmOMGLQvjqKVhtZSP62mquusu1wP8dtNseng5Tj2uAIqf4QfZyWI/p5MZkZ8obbLlCupudx6MYCDko5RwQqJntA3uFkJcI/iuHtJ7yxi7zdJJwiWmNuKEwX5PLFJguqMyA/RU6HvsPlNdWwqMsaMLNCINxP8AP91XqyjRIncZ/2+n4wILE0NQKp4sS9bWHB/VP5mLfg5NIBF29XM+atW+njjPxgU1gGyp/ceLTIOvWmkH0jEUk6mNSidK+w13ikY3weZF+O58e7LzrO22DXyWpQ5KrU2vCT/w0Av/vOYteSZj+B4yDo4lz3j+JilDvvgIdzVWMdugu9MUGzlx8cpyC0Hit7oqDyFdJ/sl0dy9eI8IS9fDMOl9w3Xt6iyuI1QXIpUuUKaxkbK7ot6BPU1zxVOs6aSRBVXNoOo/hyYiUnmuO/MP216GWup8IJLVcShWive/vg+8uDkocho/mEgf6NAmp5raC+UA4M5liKJjvAx5f2ejfxD5NNL1itFutUtDSTTXzgxNOuFNotKN1/YavT7uox+4Dd7WdNkVN3gvcgu8h3HGg4T3h6r3LgYLDgNUeZ0=
env:
  global:
    secure: j5GVM0H2OaP5BtUfOEBYwpnh2Zc4PRcWnGhgMXY2xQ90whjE/j7TxvYSQjBxfm49wldbiOK6/AcE3MmJdJtwTGooRqbGB+cbi7rCR3J9rvmj0vOhqmTkZGRroNM9/aWsSTE0SNe8R+Noq6OuwZQcbPr4E5sZqzMMQwtpXFKHyYRhGzrsQ5dWRKjhOTWBBkT0VwyVdY2VnRy5iA+u5TXzqEJlQ5oCZWjToRIQzdu5megU9XUNiZ9nhe20h2L4cv7hDPpix7h+d1KlGHhK70h50vpk0wAVvyrP7hH6FQjj2512vs5h51CoJ9Nww2A3XCcgAe0yU1NCHIqSwrqL6xF9Hx17cvWv/okGQQtZBJXcO82dQZ3L/fguhNPH8LIgrY708TqdtuQ5VRmWb6CQOJfqM86f6ZK0sdthdQqHSeQDQPx6UU+rpDjCzP2ubMr+nWOTmw3GtbDteFIdWUmoZMv8RM0ndZM0ilc7o/Lw865zD8SBSQN6kvctxQRsq3mKXecewIewsFJYd+HpVzyADAizyO1+QnGnL1jYs4azQS0vY5cB//h/c5lzILevDuC79R3aPV9McafOCMWw7sUWe2iyapSDJo9SpPLN37L4zi2Mwq3tAGln4iEG9QJ4a+lg4yqUlc27i52yJmOAqU4Db0eHjwcYNesF7JxCjLHE+s2fD8M=
