version: 2

workflows:
  version: 2
  test:
    jobs:
      - run_tests
  deploy:
    jobs:
      - run_tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - run_deploy:
          requires:
            - run_tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
jobs:
  run_tests:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build the app
          command: make up
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Install Solr Documents
          command: make load-data
      - run:
          name: Run relevancy Tests
          command: make test
  run_deploy:
    docker:
      - image: cimg/python:3.7.11
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "47:44:3f:10:e0:07:49:8b:d3:58:cd:72:2d:de:88:e0"
      - run:
          name: Build configuration asset
          command: make zip
      - run:
          name: Deploy configuration asset to SolrCloud
          command: bash .circleci/deploy.sh
