name: Deploy

on:
  push:
    tags:
      - "[0-9]+"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.ref_name }}
      SOLR_USER: ${{ secrets.SOLR_USER }}
      SOLR_PASSWORD: ${{ secrets.SOLR_PASSWORD }}
    strategy:
      matrix:
        python-version: [ "3.12" ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Build configuration asset
        run: make zip-github
      
      - name: Deploy configuration asset to SolrCloud
        run: make deploy
